### ISSUE TITLE
unable to fit templates 

### ISSUE THREAD

**Issue by Amidn** [threeML/hawc_hal#63]
macOS catalina
conda: 4.9.2
Xcode:  12.0.1 

(The same problem happens on UMD)

pytest --pyargs threeML: 148 passed, 18 skipped, 2 xfailed, 4 xpassed, 2096 warnings in 986.32s (0:16:26)
pytest --pyargs astromodels: 104 passed, 1 skipped, 107 warnings in 40.51s
test HAL: 1 passed, 363 warnings in 708.12s (0:11:48)

Problem:
While the code workes properly to fit PS and Extended sources, it is unable to fit a template using "SpatialTemplate_2D()",
It is not able nor to fit nor subtracting a previously fitted template.
(I tried ROOT and minunit)

Amid
[temp_fit.txt](https://github.com/threeML/hawc_hal/files/6221091/temp_fit.txt)

**Comment by henrikef** [comment]
Hi Amid, the information you provided is not enough to reproduce the issue.

Please provide your user scripp + relevant files such as the fits files you are loading etc.

**Comment by Amidn** [comment]
Hi Henrike, 
you can find the additional information here : "/data/disk01/home/amid/HAL_test" 
Regards

**Comment by henrikef** [comment]
Hi Amid!

This is not a HAL issue.

The main problem is that your template isn't normalized as expected. It should be normalized so that the sum of the template values times the pixel area (in steradians) comes out to 1. Future versions of astromodels will emit a warning in this case, see https://github.com/threeML/astromodels/pull/148 . Please let me know if you need any help in normalizing the template. 

Additionally, there was a bug in astromodels that cut off the non-integer part of the template. This too will be fixed in upcoming versions, see https://github.com/threeML/astromodels/pull/148

Last, please do not touch the `hash` parameter of the 2D template. It is set when the template is read in. If you reset it, you will run into issues if you ever read in multiple templates in the same script.

**Comment by henrikef** [comment]
@Amidn were you able to resolve this?

**Comment by Amidn** [comment]
I am testing and collecting the issues (If I cannot fix them by my self),
and I will come back to you,
Thank you
